server:
  port: 8082

spring:
  application:
    name: course-service

logging:
  file:
    name: C:/elk/course.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
