server:
  port: 8083

spring:
  application:
    name: eclass-service

logging:
  file:
    name: C:/elk/eclass.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
