server:
  port: 8081

spring:
  application:
    name: student-service

logging:
  file:
    name: C:/elk/student.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
